apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - database.yaml
  - traffic-ingest.yaml
  - analytics-engine.yaml
  - alert-manager.yaml
  - observability-frontend.yaml
  - network-policies.yaml
  - pod-disruption-budget.yaml
