apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traffic-ingest.fullname" . }}
  labels:
    {{- include "traffic-ingest.labels" . | nindent 4 }}
data:
  ANALYTICS_URL: {{ .Values.config.analyticsURL | quote }}
  HTTP_CLIENT_TIMEOUT: {{ .Values.config.httpClientTimeout | quote }}
