apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: advanced-observability
resources:
  - ../../base
images:
  - name: ckad/traffic-ingest
    newTag: dev-1.0.0
  - name: ckad/traffic-ingest-canary
    newTag: dev-1.1.0
  - name: ckad/analytics-engine
    newTag: dev-1.0.0
  - name: ckad/alert-manager
    newTag: dev-1.0.0
  - name: ckad/observability-frontend
    newTag: dev-1.0.0
replicas:
  - name: traffic-ingest
    count: 2
  - name: traffic-ingest-canary
    count: 1
  - name: analytics-engine
    count: 1
  - name: alert-manager
    count: 1
  - name: observability-frontend
    count: 1
