apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: day4-data
  namespace: ckad-labs
  labels: {lab: "4.4"}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
