apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-bg-blue
  namespace: ckad-labs
spec:
  replicas: 2
  selector:
    matchLabels: {app: traffic-ingest-bg, version: blue}
  template:
    metadata:
      labels: {app: traffic-ingest-bg, version: blue}
    spec:
      securityContext: {runAsNonRoot: true, runAsUser: 65532, runAsGroup: 65532}
      containers:
        - name: app
          image: ckad/traffic-ingest:local
          ports: [{name: http, containerPort: 8080}]
          env:
            - {name: HTTP_ADDR, value: ":8080"}
            - {name: ANALYTICS_URL, value: "http://analytics-engine.advanced-observability.svc.cluster.local:8081"}
          resources:
            requests: {cpu: 25m, memory: 24Mi}
            limits: {cpu: 200m, memory: 96Mi}
          readinessProbe:
            httpGet: {path: /health/ready, port: http}
            periodSeconds: 3
