apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observer-demo.fullname" . }}
  labels:
    {{- include "observer-demo.labels" . | nindent 4 }}
data:
  index.html: {{ .Values.message | quote }}
