apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observer-demo.fullname" . }}
  labels:
    {{- include "observer-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "observer-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "observer-demo.selectorLabels" . | nindent 8 }}
        lab: "5.4"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - {name: http, containerPort: 8080}
          readinessProbe:
            httpGet: {path: /, port: http}
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
              readOnly: true
            - {name: nginx-tmp, mountPath: /tmp}
            - {name: nginx-cache, mountPath: /var/cache/nginx}
      volumes:
        - name: content
          configMap:
            name: {{ include "observer-demo.fullname" . }}
        - {name: nginx-tmp, emptyDir: {}}
        - {name: nginx-cache, emptyDir: {}}
