replicaCount: 1

image:
  repository: ckad/observability-frontend
  tag: "1.0.0"
  pullPolicy: IfNotPresent

sidecars:
  initImage: busybox:1.37
  logImage: busybox:1.37
  nginxImage: nginxinc/nginx-unprivileged:1.27-alpine

service:
  type: NodePort
  port: 8083
  appPort: 18083
  nodePort: 30083

config:
  analyticsURL: http://analytics-engine:8081
  alertManagerURL: http://alert-manager:8082
  httpClientTimeout: 5s

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: observability.local
  frontendPath: /
  metricPath: /api/v1/metrics
  trafficServiceName: traffic-ingest
  trafficServicePort: 8080
  tls: []

resources:
  app:
    requests: {cpu: 25m, memory: 24Mi}
    limits: {cpu: 150m, memory: 96Mi}
  init:
    requests: {cpu: 5m, memory: 4Mi}
    limits: {cpu: 25m, memory: 16Mi}
  logSidecar:
    requests: {cpu: 5m, memory: 4Mi}
    limits: {cpu: 25m, memory: 16Mi}
  nginx:
    requests: {cpu: 10m, memory: 16Mi}
    limits: {cpu: 100m, memory: 64Mi}

podDisruptionBudget:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: true
  analyticsPodSelector: {app: analytics-engine}
  alertManagerPodSelector: {app: alert-manager}

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
