{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "analytics-engine.fullname" . }}
  labels:
    {{- include "analytics-engine.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "analytics-engine.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.trafficPodSelector | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.frontendPodSelector | nindent 14 }}
      ports:
        - {protocol: TCP, port: {{ .Values.service.port }}}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.alertManagerPodSelector | nindent 14 }}
      ports:
        - {protocol: TCP, port: 8082}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
{{- end }}
