replicaCount: 1

image:
  ref: ckad/traffic-ingest:local
  pullPolicy: IfNotPresent

message: release-v1

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 64Mi
