{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "observability-db.fullname" . }}
  labels:
    {{- include "observability-db.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "observability-db.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.alertManagerPodSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
{{- end }}
